CREATE TABLE IF NOT EXISTS HospitalData (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    LastUpdated DATE,
    AsOfDate DATE,
    Version VARCHAR(50),
    Location VARCHAR(255),
    Address VARCHAR(255),
    License VARCHAR(255),
    FinancialAid VARCHAR(255),
    Belief BOOLEAN
);

CREATE TABLE IF NOT EXISTS HospitalBody (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    HospitalDataId INT,
    Description VARCHAR(255),
    Code1 VARCHAR(50),
    Code1Type VARCHAR(50),
    Code2 VARCHAR(50),
    Code2Type VARCHAR(50),
    Code3 VARCHAR(50),
    Code3Type VARCHAR(50),
    BillingClass VARCHAR(50),
    Setting VARCHAR(50),
    DrugUnitOfMeasurement VARCHAR(50),
    DrugTypeOfMeasurement VARCHAR(50),
    StandardChargeGross DECIMAL(10, 2),
    StandardChargeDiscountedCash DECIMAL(10, 2),
    PayerName VARCHAR(255),
    PlanName VARCHAR(255),
    Modifiers VARCHAR(255),
    StandardChargeNegotiatedDollar DECIMAL(10, 2),
    StandardChargeNegotiatedAlgorithm VARCHAR(255),
    StandardChargeNegotiatedPercentage DECIMAL(5, 2),
    StandardChargeMin DECIMAL(10, 2),
    StandardChargeMax DECIMAL(10, 2),
    CountOfComparedRates INT,
    StandardChargeMethodology VARCHAR(255),
    AdditionalGenericNotes TEXT,
    Footnote TEXT
);